### ISSUE TITLE
主机如何访问在虚拟机中通过Webpack打包好的网站

### ISSUE THREAD

**Issue by londbell** [zhangmengxue/React-Code-Snippet#1]
您好，我在学习您的React-Learning中的内容，遇到了一个问题，那就是通过Vmware设置了端口转发后，无法在宿主机上访问http://localhost:8888/webpack-dev-server/，虚拟机中的火狐是可以的。请问这是要追加什么设置吗？
![qq 20150930112701](https://cloud.githubusercontent.com/assets/7590762/10183781/64ff2c7e-6766-11e5-95bb-884337a32cab.png)
![qq 20150930112849](https://cloud.githubusercontent.com/assets/7590762/10183789/715e2786-6766-11e5-89c2-4f59221d5d4e.png)
![qq 20150930112859](https://cloud.githubusercontent.com/assets/7590762/10183793/76f2d250-6766-11e5-8cd3-68158a6fabf6.png)

**Comment by zhangmengxue** [comment]
端口号是8080，你在火狐浏览器中访问时是对的。下面的图中端口号变成了8888，所以访问不了。

在 2015年9月30日 上午11:29，一个PR都不给我过,好坏好坏的 <notifications@github.com>写道：

**Comment by londbell** [comment]
我的转发规则是8080到8888,是因为一开始转发到8080访问不了，就换到了8888，还是无法访问。请问是webpack有什么监听设置吗？

**Comment by zhangmengxue** [comment]
我没有做别的配置，用的默认端口。如果你在虚拟机中访问有问题的话，建议用charles代理调试下。

**Comment by zhoupeihuang** [comment]
求你做师傅，不知道你答应不答应！【QQ:625506370】，师傅在上，请受徒儿一拜

**Comment by kuiniela** [comment]
你现在知道怎么回事了吗

**Comment by zhoupeihuang** [comment]
给我原文地址，邮件太多



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月19日(周一) 下午3:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhangmengxue/React-Code-Snippet] 主机如何访问在虚拟机中通过Webpack打包好的网站 (#1)




 
你现在知道怎么回事了吗
